AUGMENTATION: True
IMAGE_SIZE: [224,224,3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 2
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
TRAINING:
  SHOULD_TRAIN: False  # Set to True when you want to train